// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ChatMessage {
    pub id: i64,
    pub sender_id: String,
    pub text: String,
    pub map_id: String,
    pub timestamp: i64,
}

impl __sdk::InModule for ChatMessage {
    type Module = super::RemoteModule;
}
