// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
pub(crate) use super::chat_message_type::ChatMessage;
use spacetimedb_sdk::__codegen::{self as __sdk, __ws};

/// Table handle for the table `chat_message`.
///
/// Obtain a handle from the [`ChatMessageTableAccess::chat_message`] method on [`super::RemoteTables`],
/// like `ctx.db.chat_message()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.chat_message().on_insert(...)`.
pub struct ChatMessageTableHandle<'ctx> {
    imp: __sdk::TableHandle<ChatMessage>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `chat_message`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ChatMessageTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ChatMessageTableHandle`], which mediates access to the table `chat_message`.
    fn chat_message(&self) -> ChatMessageTableHandle<'_>;
}

impl ChatMessageTableAccess for super::RemoteTables {
    fn chat_message(&self) -> ChatMessageTableHandle<'_> {
        ChatMessageTableHandle {
            imp: self.imp.get_table::<ChatMessage>("chat_message"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ChatMessageInsertCallbackId(__sdk::CallbackId);
pub struct ChatMessageDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ChatMessageTableHandle<'ctx> {
    type Row = ChatMessage;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ChatMessage> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ChatMessageInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ChatMessageInsertCallbackId {
        ChatMessageInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ChatMessageInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ChatMessageDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ChatMessageDeleteCallbackId {
        ChatMessageDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ChatMessageDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ChatMessage>("chat_message");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<ChatMessage>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ChatMessage>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}
