// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib};

use super::vector_2_type::Vector2;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PlayerEntity {
    pub entity_id: u32,
    pub player_id: u32,
    pub direction: Vector2,
    pub speed: f32,
    pub last_split_time: __sdk::Timestamp,
}

impl __sdk::InModule for PlayerEntity {
    type Module = super::RemoteModule;
}
