// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::player_entity_type::PlayerEntity;
use spacetimedb_sdk::__codegen::{self as __sdk, __ws};

/// Table handle for the table `player_entity`.
///
/// Obtain a handle from the [`PlayerEntityTableAccess::player_entity`] method on [`super::RemoteTables`],
/// like `ctx.db.player_entity()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.player_entity().on_insert(...)`.
pub struct PlayerEntityTableHandle<'ctx> {
    imp: __sdk::TableHandle<PlayerEntity>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `player_entity`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PlayerEntityTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PlayerEntityTableHandle`], which mediates access to the table `player_entity`.
    fn player_entity(&self) -> PlayerEntityTableHandle<'_>;
}

impl PlayerEntityTableAccess for super::RemoteTables {
    fn player_entity(&self) -> PlayerEntityTableHandle<'_> {
        PlayerEntityTableHandle {
            imp: self.imp.get_table::<PlayerEntity>("player_entity"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PlayerEntityInsertCallbackId(__sdk::CallbackId);
pub struct PlayerEntityDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PlayerEntityTableHandle<'ctx> {
    type Row = PlayerEntity;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PlayerEntity> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PlayerEntityInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerEntityInsertCallbackId {
        PlayerEntityInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PlayerEntityInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PlayerEntityDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerEntityDeleteCallbackId {
        PlayerEntityDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PlayerEntityDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PlayerEntity>("player_entity");
    _table.add_unique_constraint::<u32>("entity_id", |row| &row.entity_id);
}
pub struct PlayerEntityUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PlayerEntityTableHandle<'ctx> {
    type UpdateCallbackId = PlayerEntityUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PlayerEntityUpdateCallbackId {
        PlayerEntityUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PlayerEntityUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<PlayerEntity>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PlayerEntity>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `entity_id` unique index on the table `player_entity`,
/// which allows point queries on the field of the same name
/// via the [`PlayerEntityEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.player_entity().entity_id().find(...)`.
pub struct PlayerEntityEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PlayerEntity, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PlayerEntityTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `player_entity`.
    pub fn entity_id(&self) -> PlayerEntityEntityIdUnique<'ctx> {
        PlayerEntityEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PlayerEntityEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<PlayerEntity> {
        self.imp.find(col_val)
    }
}
