// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::starter_area_type::StarterArea;
use spacetimedb_sdk::__codegen::{self as __sdk, __ws};

/// Table handle for the table `starter_area`.
///
/// Obtain a handle from the [`StarterAreaTableAccess::starter_area`] method on [`super::RemoteTables`],
/// like `ctx.db.starter_area()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.starter_area().on_insert(...)`.
pub struct StarterAreaTableHandle<'ctx> {
    imp: __sdk::TableHandle<StarterArea>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `starter_area`.
///
/// Implemented for [`super::RemoteTables`].
pub trait StarterAreaTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`StarterAreaTableHandle`], which mediates access to the table `starter_area`.
    fn starter_area(&self) -> StarterAreaTableHandle<'_>;
}

impl StarterAreaTableAccess for super::RemoteTables {
    fn starter_area(&self) -> StarterAreaTableHandle<'_> {
        StarterAreaTableHandle {
            imp: self.imp.get_table::<StarterArea>("starter_area"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct StarterAreaInsertCallbackId(__sdk::CallbackId);
pub struct StarterAreaDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for StarterAreaTableHandle<'ctx> {
    type Row = StarterArea;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = StarterArea> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = StarterAreaInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StarterAreaInsertCallbackId {
        StarterAreaInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: StarterAreaInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = StarterAreaDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StarterAreaDeleteCallbackId {
        StarterAreaDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: StarterAreaDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<StarterArea>("starter_area");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<StarterArea>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<StarterArea>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}
