// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct StarterArea {
    pub id: String,
    pub width: i32,
    pub height: i32,
    pub arrival_x: i32,
    pub arrival_y: i32,
}

impl __sdk::InModule for StarterArea {
    type Module = super::RemoteModule;
}
